after_success:
  - npm run coverage
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
language: node_js
node_js:
  - node
  - 13
notifications:
  email: false
script:
  - npm run build
  - npm run test
services:
  - mongodb