after_success:
  - npm run coverage
jobs:
  include:
    - stage: release
      deploy:
        on:
          all_branches: true
        provider: script
        script:
          - npx semantic-release
        skip_cleanup: true
      node_js: lts/*
language: node_js
node_js:
  - node
  - lts/*
notifications:
  email: false
script:
  - npm run build
  - npm run test
services:
  - mongodb
